### ISSUE TITLE
No Driver found for Cp210x

### ISSUE THREAD

**Issue by iksheth** [kai-morich/SimpleUsbTerminal#1]
Hi I am Trying to connect Cp210x to my Android device when I install this app and tried to connect device it does detect USB but it says No Driver.

**Comment by kai-morich** [comment]
if your device has a non-standard VID/PID you have to add a mapping in the CustomProber class specifiyng the correct driver class

**Comment by iksheth** [comment]
Problem Solved, It Helped Thank you. :)
