### ISSUE TITLE
FTDI FT2232H   support?

### ISSUE THREAD

**Issue by maxelrad** [kai-morich/SimpleUsbTerminal#10]
Sorry - my mistake in the prior question.

**Comment by maxelrad** [comment]
To clarify my issue,  the FT2232H is the USB hardware in the BeagleBone Black.  I would to communicate with it from an Android Tablet.  
I have found reference to the FT2232H in usbSerialForAndroid com.hoho.android.usbserial src main java driver FtdiSerialDriver
It is not listed in the DeviceFilter.xml.
My level of expertise is limited - Is there an existing driver available that can be accessed? 

thank you

**Comment by kai-morich** [comment]
Ft2232 is supported by the FTDI driver

**Comment by kai-morich** [comment]
I will update the devicefilter.xml

**Comment by kai-morich** [comment]
device filter updated with 79ecd1bc73aed04827eccd7fdc187ca7dc8f6cd2
