### ISSUE TITLE
Error: "Connection failed: Setting baudrate failed: result=‑1" ESP32

### ISSUE THREAD

**Issue by meltdown03** [kai-morich/SimpleUsbTerminal#11]
I am no longer to connect [Serial USB Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal) to my ESP32 DevKitC-V4 using my Samsung Galaxy S9 running Android 10.0. My ESP32 uses a CP2102N UART module. I am positive it worked before but now I can't get it connected. I get the following error:
`Connection failed: Setting baudrate failed: result=‑1`
I don't remember when it last worked, but my ESP8266 which uses a CP2102 UART module works fine. I also tried a couple other USB Terminal Apps from the Google Play store such as "Pytool USB Serial" which work fine but aren't as nice as your app. I've tried different cables and adapters, but nothing works. I have the baud rate and other serial settings set correctly as 115200, 8-N-1.

**Comment by kai-morich** [comment]
Hi

my app uses the usb-serial-for-android library, but there have been no signficant changes to cp2102 initialization here: https://github.com/mik3y/usb-serial-for-android/commits/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/Cp21xxSerialDriver.java

Are you really sure that it worked before?

Kai Morich

29.02.2020 01:35:13 Neal MIller <notifications@github.com>:

**Comment by meltdown03** [comment]
I'm sure it worked before and other USB Terminal apps work also. Do you know what that error means?

**Comment by meltdown03** [comment]
I've been building the SimpleUSBTerminal app from source and found the commit#  `8c7f14b` broke it, the one before works so it must be related to the changes from usb-serial-for-android update from 2.0.0 to 2.1.0. Should I goto that repo and open an issue?

**Comment by meltdown03** [comment]
If I revert these lines to the commit before, I can get it to work:
https://github.com/mik3y/usb-serial-for-android/blob/17c3d406051006177bd37b65742a1b8d134073c1/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/Cp21xxSerialDriver.java#L131-L138

**Comment by kai-morich** [comment]
the error message 'Setting baudrate failed' is misleading, as the `setConfigSingle` method is called from various places.. Please share the callstack. In 'Serial USB Terminal` you can enable display of call stack with long click on &#9776; -> Info -> OK

According to Silabs the CP2102N should be a drop in replacement for CP2102, but maybe the library sends a command that is not correct or not supported and more and your case would be ok if it is ignored.

**Comment by kai-morich** [comment]
looks like no other implementation uses BAUDDIV command. please try with commented out:

    setConfigSingle(SILABSER_SET_BAUDDIV_REQUEST_CODE, BAUD_RATE_GEN_FREQ / DEFAULT_BAUD_RATE);

**Comment by meltdown03** [comment]
```

06:31:04.826 USB device detected
06:31:06.782 Connection failed: Setting baudrate failed: result=‑1
java.io.IOException: Setting baudrate failed: result=‑1
  at com.hoho.android.usbserial.driver.Cp21xxSerialDriver$Cp21xxSerialPort.setConfigSingle(Cp21xxSerialDriver.java:2)
  at com.hoho.android.usbserial.driver.Cp21xxSerialDriver$Cp21xxSerialPort.openInt(Cp21xxSerialDriver.java:13)
  at com.hoho.android.usbserial.driver.CommonUsbSerialPort.open(CommonUsbSerialPort.java:3)
  at de.kai_morich.serial_usb_terminal.l.a(TerminalFragment.java:20)
  at de.kai_morich.shared.s1.onOptionsItemSelected(TerminalFragmentBase.java:5)
  at android.app.Fragment.performOptionsItemSelected(Fragment.java:2681)
  at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3189)
  at android.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:373)
  at android.app.Activity.onMenuItemSelected(Activity.java:4198)
  at android.support.v4.app.g.onMenuItemSelected(FragmentActivity.java:1)
  at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:1)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:1)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:1)
  at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:1)
  at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:2)
  at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:2)
  at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
  at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:2)
  at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
  at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1)
  at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:1)
  at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
  at android.view.View.performClick(View.java:7870)
  at android.widget.TextView.performClick(TextView.java:14956)
  at android.view.View.performClickInternal(View.java:7839)
  at android.view.View.access$3600(View.java:886)
  at android.view.View$PerformClick.run(View.java:29363)
  at android.os.Handler.handleCallback(Handler.java:883)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at android.os.Looper.loop(Looper.java:237)
  at android.app.ActivityThread.main(ActivityThread.java:7811)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```
Removing that line fixes it, do that may be it.

**Comment by kai-morich** [comment]
fixed with https://github.com/mik3y/usb-serial-for-android/commit/2cad1fd5a28f66993d7787eb68f86e2e9058c3e9
