### ISSUE TITLE
Asynchronous Data Reception Code

### ISSUE THREAD

**Issue by ShivrajJadhav-Cloud** [kai-morich/SimpleUsbTerminal#12]
Hello Kai Morich, 
Can you please tell me in which file exactly in the USB-Serial library is the asynchronous data reception code? I tried to figure out but was unable to do so. Thanks in Advance.

**Comment by kai-morich** [comment]
the [SerialInputOutputManager](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/util/SerialInputOutputManager.java) class running in a separate thread does the async receive. It is started in the [SerialSocket](https://github.com/kai-morich/SimpleUsbTerminal/blob/master/app/src/main/java/de/kai_morich/simple_usb_terminal/SerialSocket.java#L52) class
