### ISSUE TITLE
Can this APP work with the device running as a USB Device

### ISSUE THREAD

**Issue by younesr1** [kai-morich/SimpleUsbTerminal#14]
Thank you for this project! I've tried this app with the device it is running on acting as a USB Host and it works great! However, when I run the app with the device it is running on acting as a USB device, it shows no device connected.

I was wondering if the app supports this use case?

**Comment by younesr1** [comment]
In other words, if I connect my Android device to a USB device, then the app works great. However, if I connect it to as USB host, then it does not detect a device. Is this expected?

**Comment by kai-morich** [comment]
no, this app only supports host mode
