### ISSUE TITLE
Serial USB Terminal displays unknown device on USB Devices page

### ISSUE THREAD

**Issue by Totoro927** [kai-morich/SimpleUsbTerminal#15]
![Screenshot_20200713_111356_de kai_morich serial_usb_terminal](https://user-images.githubusercontent.com/20111460/87388716-e511a200-c5d7-11ea-87d7-4e110aa99bfc.png)
Hi, there is no problem in using the Serial USB Terminal, but I failed to use the Simple Usb Terminal.
Can you tell me what the OK button do in Serial USB Terminal?
If you can give me some codes about OK button's operation to refer to is better. 
Thank you.

**Comment by kai-morich** [comment]
You have to choose the appropriate driver for this unknown device. If it is not a serial device it will not work.
In simple usb terminal there is no such dialog and you have to enhance the code and add the VID/PID to the CustomProber class

**Comment by Totoro927** [comment]
> You have to choose the appropriate driver for this unknown device. If it is not a serial device it will not work.
> In simple usb terminal there is no such dialog and you have to enhance the code and add the VID/PID to the CustomProber class


I have used the VID/PID in Custom Prober.java. Do I need to change the VID/PID?
I used the following codes 

_UsbSerialProbe usbCustomProber = CustomProber.getCustomProbe();
UsbSerialDriver driver = usbDefaultProber.probeDevice(device);_

how can I  choose the appropriate driver for this unknown device?

**Comment by kai-morich** [comment]
the CustomProber class is part of this project. There you have to add your VID/PID and driver class name

**Comment by Totoro927** [comment]
I use my device's VID/PID. Then I can connect my device. Thank you very much.
