### ISSUE TITLE
PL230 - SerialUSB Gets Data Reply, SimpleUSB connects but fails to get Data reply

### ISSUE THREAD

**Issue by rokkamraja** [kai-morich/SimpleUsbTerminal#18]
Playstore App SerialUsbTerminal with BaudRate 9600, HEX Mode and CR+LF connects to PL2303 USB device and sends data to our BMS device and receives output too. Attaching pics for reference.

However, the same SimpleUSB - We jus cloned the repo and built the app - set BaudRate to 9600 is connecting and sending but not able to receive the output. What could be the reason ? How can we test easily using emulator ?

![WhatsApp Image 2020-07-29 at 6 33 26 AM](https://user-images.githubusercontent.com/2141672/89288344-1d564e80-d673-11ea-8a64-a4003479cd33.jpeg)
![WhatsApp Image 2020-07-29 at 6 33 27 AM (1)](https://user-images.githubusercontent.com/2141672/89288348-1e877b80-d673-11ea-8600-96b377b728a0.jpeg)
![WhatsApp Image 2020-07-29 at 6 33 27 AM (2)](https://user-images.githubusercontent.com/2141672/89288351-1fb8a880-d673-11ea-9496-15f7b9389f2a.jpeg)
![WhatsApp Image 2020-07-29 at 6 33 27 AM](https://user-images.githubusercontent.com/2141672/89288358-20513f00-d673-11ea-8d16-b9591772ea44.jpeg)
![WhatsApp Image 2020-07-29 at 6 30 28 AM](https://user-images.githubusercontent.com/2141672/89288369-26dfb680-d673-11ea-8b55-3984bdfc4655.jpeg)
![WhatsApp Image 2020-08-02 at 7 47 40 PM](https://user-images.githubusercontent.com/2141672/89288371-27784d00-d673-11ea-9268-bcc0cd5ea9df.jpeg)

**Comment by kai-morich** [comment]
SimpleUsbTerminal does not come with HEX mode, so your device got the A5 03 .... as plain string
