### ISSUE TITLE
permission handling on device connection

### ISSUE THREAD

**Issue by Gobink6** [kai-morich/SimpleUsbTerminal#21]
If the phone is rebooted, but the cable remains plugged in, and then the app is opened, the pop up will come back.
If the USB cable is unplugged, upon replugging the pop up does not come back.
However, if the app is closed, but the cable remains plugged in, and then the app is reopened, the pop up does not come back.

**Comment by kai-morich** [comment]
Android caches the permission. do you have connection issues?

**Comment by Gobink6** [comment]
I did not have a connection issue, the first time I gave a USB permission, every time I reboot the device the cable remains plugged in the device and then the app is opened, the USB permission pop up will come back, If I unplugged USB cable and replugged the USB permission pop up does not come back.

**Comment by kai-morich** [comment]
the app cannot influence how Android caches the permission
