### ISSUE TITLE
How to convert rs232 data to string

### ISSUE THREAD

**Issue by jitenders859** [kai-morich/SimpleUsbTerminal#23]
I have tried your applications and it works great with my weighbridge machine its shows weight in mobile device using rs232 to usb cable

I have implemented the Library mik3y/usb-serial-for-android in my flutter app and trying to receive data I am getting the data but when I try to convert the data to string it shows me random string not the weight 

I tried using TextUtil file and used TextUtil.toHexString(data) function but still shows random strings not the weight of weighbridge

   private final SerialInputOutputManager.Listener mListener = new SerialInputOutputManager.Listener() {

        @Override
        public void onRunError(Exception e) {
            Log.d(TAG, "Runner stopped.");
        }

        @Override
        public void onNewData(byte[] data) {
            runOnUiThread(() -> {
                if (m_EventSink != null) {
                    // String msg = new String(data);
                    m_EventSink.success(TextUtil.toHexString(data) + '\n');
                }
            });
        }
    };
    
when I  am using 
var msg = String(data)
it stops the app how can I solve this issue please let me know.

**Comment by kai-morich** [comment]
`new String(data)` is correct. The same is used [here](https://github.com/kai-morich/SimpleUsbTerminal/blob/ed4cf127908aee07f666fcb9073552b22ac54ad5/app/src/main/java/de/kai_morich/simple_usb_terminal/TerminalFragment.java#L334). Maybe it's an issue on flutter side, or you have wrong baud rate in your app

**Comment by kai-morich** [comment]
closed due to inactivity
