### ISSUE TITLE
Raspberry pi zero W not detected

### ISSUE THREAD

**Issue by Mhowser** [kai-morich/SimpleUsbTerminal#24]
I followed this guide to set up serial access over USB https://learn.adafruit.com/turning-your-raspberry-pi-zero-into-a-usb-gadget/serial-gadget

The app does not detect a device. I know the USB otg adaptor and cable work and I am plugged in to the USB data port on the PI Zero.

**Comment by kai-morich** [comment]
have you checked with a Windows or Linux computer that the USB serial port on your Pi Zero is working?

**Comment by kai-morich** [comment]
closed due to inactivity
