### ISSUE TITLE
the code is not upto date with the app 

### ISSUE THREAD

**Issue by jitenders859** [kai-morich/SimpleUsbTerminal#27]
The code is not upto date with the app the newline names and newline values have 6 fields in app but here I can only see 3 

can you update it or let me know what would be value for the rest of the fields

 <string-array name="newline_names">
        <item>CR+LF</item>
        <item>LF</item>
        <item>&lt;none&gt;</item>
    </string-array>
    <string-array name="newline_values">
        <item>\u000d\u000a</item>
        <item>\u000a</item>
        <item></item>
    </string-array>
    

the newline values in app are
CR+LF
CR
LF
STX/ETX
NUL
None

**Comment by kai-morich** [comment]
You can find the actual values in any ASCII reference table.
It's unlikely to add more than the usual newline values to this simplified version of the app in this repo, as newline detection for STX/ETX would bloat the code

**Comment by jitenders859** [comment]
ok thanks
