### ISSUE TITLE
unable to set setReadTimeout and setWriteTimeout

### ISSUE THREAD

**Issue by jitenders859** [kai-morich/SimpleUsbTerminal#28]
I am using mik3y/usb-serial-for-android library

but the data I am receiving is in single characters I tried to set setReadTimeout like this but its not working.

 mSerialIoManager = new SerialInputOutputManager(port, mListener);
 mSerialIoManager.setReadTimeout(200);

**Comment by kai-morich** [comment]
the data is received in arbitrary chunks, see https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time
