### ISSUE TITLE
Mobile app shutdown as soon as I remove the microusb

### ISSUE THREAD

**Issue by jitenders859** [kai-morich/SimpleUsbTerminal#29]
I am using rs232 to usb and receiving data from it.

sometimes when receiving the data and I remove the cable the mobile shutdown. I am facing it both with your app and the app that I am trying to develop how can I solve it.

Thanks

**Comment by kai-morich** [comment]
when disconnected, the fragment is notified with `onSerialIoError`. it typically only terminates when there is an unhandled exception. Please check output in Logcat window in Android Studio
