### ISSUE TITLE
No Device Recognize in Android 10

### ISSUE THREAD

**Issue by muhammadfarooq012012** [kai-morich/SimpleUsbTerminal#33]
I am using Android 10. I am trying to attach the USB device using an OTG adapter to the app. No USB device message appears and no device shows in the list of USB devices.

The USB device shows When I run this app Below Android 10.

**Comment by kai-morich** [comment]
I am not aware of general issues with Android 10.
I asume it's more related to Android device vendor and vendor specific customization of Android.
Did you test with same device running different Android versions?
