### ISSUE TITLE
android app data reception slows down after a while

### ISSUE THREAD

**Issue by mzcphoenix** [kai-morich/SimpleUsbTerminal#36]
Hi, I was using your driver for an android app to receive CANBUS data. The can speed is 500k baud. But after a while the USB data reception is slowing down.. could you please think of any issues ? It's been two weeks I am trying but without much progress. The device I am trying to use is : https://www.alibaba.com/product-detail/Android-Car-Player-Touch-screen-USB_1600120601898.html?spm=a2700.pc_countrysearch.main07.66.db2fecbadYNr4Z

**Comment by kai-morich** [comment]
UI display significantly slows down, when only appending data to text widget without truncating older data.

**Comment by mzcphoenix** [comment]
Thanks for your reply. In my test actually I counted the time it requires to send 10000 CAN message, during each send the time increases in the android side (from arduino it's the same every time). I didn't print in the UI even, just printed in the logcat and counted the time after all messages send complete. wondering if there are any issues with the hardware or android os :s
