### ISSUE TITLE
Help to insert the values

### ISSUE THREAD

**Issue by DocMeaningless** [kai-morich/SimpleUsbTerminal#38]
Hello.
I am trying to use this app to send a command to a device connected to an USB port.
Thanks to the app i can see the device but i do not understand how i need to insert the byte to execute the command.
I need to send 186 2 1 185.
Could you please explain me how to do that?

**Comment by kai-morich** [comment]
If you want to send bytes with ascii value 186 2 ... please try HEX mode with values BA 02 ..

**Comment by DocMeaningless** [comment]
Thank you for your answer.
The problem was the device that does not work correctly with Android.
