### ISSUE TITLE
Android 10-11 does not recognize USB

### ISSUE THREAD

**Issue by GMejoras** [kai-morich/SimpleUsbTerminal#42]
The driver does not work for a FTDI RS232 cable. I've tries in Android 10 and 11 in some differents terminals and does not work.

I've also tried with Simple USB Terminal with no luck.

Is there any new driver or something to use it with the new Android Version?

**Comment by kai-morich** [comment]
have you checked your devices with other Apps, e.g.  [Serial USB Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal) or connected to a Windows / Linux PC?
