### ISSUE TITLE
Strange characters on terminal after sending command

### ISSUE THREAD

**Issue by javierxio** [kai-morich/SimpleUsbTerminal#44]
Hello. I am using the app and can connect to the PL2303 device. I have set the baud rate to 115200.

When I send my hex commands `F6 30 01 0A 31 6F` the terminal prints strange characters. Ex:  ?^A^A^@?o

Any ideas what I am doing wrong? Thanks.

**Comment by kai-morich** [comment]
the app can work in text _or_ hex mode. if text is displayed, you probably haven't switched to hex mode and you have send your input as is (17 characters) instead of 6 bytes

**Comment by javierxio** [comment]
Kai, my OS is AOSP 9.0. I am running your app on my device. I am able to communicate with my target using Docklight software running on Windows but cannot communicate with your app on android.

**Comment by kai-morich** [comment]
are you using this SimpleUsbTerminal app or my [Serial USB Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal) app?
Please compare baud rate and other options with your windows software

**Comment by javierxio** [comment]
@kai-morich Thanks for the SimpleUsbTerminal suggestion. I found that my settings were not correct specifically "Newline" should have been set to None. 

OK to close.

![image](https://user-images.githubusercontent.com/63758477/183141345-c0e4c64a-d967-4ade-bf75-4aaad7328c32.png)

**Comment by javierxio** [comment]
One other observation, the output of the terminal seems to wrap around in one continuous line. It is not critical but if I am missing a setting, please let me know.

![image](https://user-images.githubusercontent.com/63758477/183142632-57e3d62c-5e60-4e8b-a73a-ee5aa058bb10.png)

**Comment by kai-morich** [comment]
that's normal with newline = None
