### ISSUE TITLE
retain connection when changing fragment or activity

### ISSUE THREAD

**Issue by kmd2410** [kai-morich/SimpleUsbTerminal#46]
I succeeded in connecting and reading data with your wonderful code.
I want to switch pages while staying connected after being connected. Can you advise me how to do it?
thank taecher..

**Comment by kmd2410** [comment]
I want to change the screen while maintaining the serial connection.

**Comment by kai-morich** [comment]
please have a look at the `service` member of the terminal fragment class. By using `setRetainInstance` this member stays valid over rotation or sending the app to background. You could also store it at the Activity or Application object.
