### ISSUE TITLE
Avoid restart of app without asking user for usb permission? 

### ISSUE THREAD

**Issue by NikhilUsadadiya** [kai-morich/SimpleUsbTerminal#48]
Hi @kai-morich 
I am getting references from your library code and I must say it is a pretty awesome lightweight app. I am stuck on one change and seeking help from your side. I want to avoid the restart of the app every time whenever a device is connected. At the start of the application, a dialog appears which contains that allows the USB terminal app to always open for this device with a checkbox. I want to avoid restarting of the app every time when the app is in the foreground already. Any help will be appreciable.

**Comment by NikhilUsadadiya** [comment]
- I have added android:launchMode="singleTask" in each activity but it still restart at the root activity.
- Also, I have removed the </meta-data ... android:resource="@xml/usb_device_filter"> but due to that it generates the permission dialog eveytime whenever it gets connected to the usb device.

Got stuck on this.

**Comment by kai-morich** [comment]
if you remove the usb_device_filter from the manifest, the 'always open app with ...' dialog will not be shown, but when you really want to connect to the device you have to confirm the permission dialog. Android does not allow without
