### ISSUE TITLE
Connection failed: baud rate to low (110baud)

### ISSUE THREAD

**Issue by Ron-e** [kai-morich/SimpleUsbTerminal#49]
is it possible to enable it to work with a baud rate of 110?
I cannot increase the baud rate on the device.

**Comment by kai-morich** [comment]
it depends on the usb-serial converter chip. some do not support such low baud rates, see `baudrate` tests [here](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/androidTest/java/com/hoho/android/usbserial/DeviceTest.java)

**Comment by Ron-e** [comment]
On my PC with the same usb-serial converter (FTDI/FT232RL) it works with a baudrate of 110 and if i try it with the app i get the message that the connection has failed. "Connection failed: baud rate to low" .

**Comment by kai-morich** [comment]
FTDI does not provide official documentation. With the available information lower baud rates are not possible
