### ISSUE TITLE
Newline error

### ISSUE THREAD

**Issue by BedrettinOrtak** [kai-morich/SimpleUsbTerminal#52]
Hi,
Ive been using your Android app SerialUSBTerminal for a while and had a few thoughts on how I would like to use it so I came here. So far this repo is good enough for what I need, theres just one problem that maybe you can help me with. When I send a message longer than one line of an Android screen, it then cuts the message into pieces. For example, if two lines are sent then two separate messages are sent. The index of the messages are changed when this happens too. 
example=
msg ="hello world,hello world,hello world,hello world,hello world,hello man"
name = msg[0]= h   //for first line
name = msg[0] = m // for second line
Ive looked through all the code to fınd where this problem might be, but to no avail.
On the Android app, there is no problem like this, so Im wondering where the difference is here.
I would really appreciate any help. Thanks.

**Comment by kai-morich** [comment]
please check https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#user-content-When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time
