### ISSUE TITLE
Java.Io.Exception Error after a long continuous run

### ISSUE THREAD

**Issue by sudeepeuphotic** [kai-morich/SimpleUsbTerminal#54]
Hi,
I have created USB as a service and through a companion object calling read and write. The communication is going on fine for sometime, But after few hours of run sometimes it's generating java.Io.Exception as below.

03-17 13:05:05.101 10537 10590 I App     : [USB] Sending : initialize 1
03-17 13:05:05.116 10537 10590 I App     : int value of parameter is 1
03-17 13:05:05.117 10537 10590 I App     : [USB] : INITIALIZE 001
03-17 13:05:05.126 10537 10590 I App     : [USB2] exception :
03-17 13:05:05.126 10537 10590 I App     : java.io.IOException: Connection closed
03-17 13:05:05.126 10537 10590 I App     : 	at com.hoho.android.usbserial.driver.CommonUsbSerialPort.write(CommonUsbSerialPort.java:212)
03-17 13:05:05.126 10537 10590 I App     : 	at com.euphotic.sbcApp.listener.UsbDeviceInstance.loadCmd(UsbDeviceInstance.kt:297)
03-17 13:05:05.126 10537 10590 I App     : 	at com.euphotic.sbcApp.listener.UsbDeviceInstance.sendData(UsbDeviceInstance.kt:343)
03-17 13:05:05.126 10537 10590 I App     : 	at com.euphotic.sbcApp.listener.UsbDeviceInstance.sendData$default(UsbDeviceInstance.kt:325)
03-17 13:05:05.126 10537 10590 I App     : 	at com.euphotic.sbcApp.activity.recipe.Cooking$generateNewCookingJob$1.invokeSuspend(Cooking.kt:373)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
03-17 13:05:05.126 10537 10590 I App     : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

This is how I am writing to the port:
port.write(command.toByteArray(), 2000)

I am using 3.4.4 version of the library
Can you please suggest a fix for this?

**Comment by kai-morich** [comment]
at CommonUsbSerialPort.java:212 the connection is already closed (=null). 
Please check if you close it somewhere else or you got another error somewhere else.
