### ISSUE TITLE
detect Usb connection

### ISSUE THREAD

**Issue by SaraEngizek** [kai-morich/SimpleUsbTerminal#58]
"How to automatically detect USB device connection in Android?

**Comment by kai-morich** [comment]
use USB_DEVICE_ATTACHED intent https://developer.android.com/guide/topics/connectivity/usb/host#manifest as also done in this app

**Comment by SaraEngizek** [comment]
Actually, what I want to ask is that I use a typc-usb cable to connect to the phone while using this application. When I unplug the module cable while the typc cable is on the phone, there is no re-detection until I unplug the typc cable and plug it back in. how can i solve this
