### ISSUE TITLE
Transfer a text file to a usb serial device.

### ISSUE THREAD

**Issue by glenn-edgar** [kai-morich/SimpleUsbTerminal#59]
I would like to use this app to control usb serial devices.  To do this i need to down load text files for actions like join and send message.  I want to use this app for lorawan signal levels of my gateway.

Can this app do send text file.

Thanks

**Comment by kai-morich** [comment]
You can do this with my [Serial USB Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal) app, but this repo is intentionally kept simple to show usage of usb-serial-for-android library
