### ISSUE TITLE
[Guidance] How to send 1 byte to the USB device

### ISSUE THREAD

**Issue by omatrot** [kai-morich/SimpleUsbTerminal#6]
I need to send a command to the device that is just one byte.

For instance, I need to send 0xf2, which is supposed to tell the device to send me data at 200Hz. By default the device sends me 20 bytes at 1Hz.

I've tried `\xf2` in the app, but this does nothing, meaning I'm still receiving 20 bytes à 1Hz.

**Comment by kai-morich** [comment]
this intentionally simple app does not support hex mode. it does not interpret the input and if you enter `\xf2` it sends 4 bytes
