### ISSUE TITLE
Build SimpleUsbTerminal: failed

### ISSUE THREAD

**Issue by nancwang** [kai-morich/SimpleUsbTerminal#61]
I clone the project and tried to build with new installed Android studio Giraffe | 2022.3.1 Patch 2. Build failed with messages

```
FAILURE: Build completed with 9 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.mik3y:usb-serial-for-android:3.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/mik3y/usb-serial-for-android/3.5.0/usb-serial-for-android-3.5.0.pom
       - https://repo.maven.apache.org/maven2/com/github/mik3y/usb-serial-for-android/3.5.0/usb-serial-for-android-3.5.0.pom
       - file:/C:/Users/xxxxxxxxxx/.m2/repository/com/github/mik3y/usb-serial-for-android/3.5.0/usb-serial-for-android-3.5.0.pom
       - https://jitpack.io/com/github/mik3y/usb-serial-for-android/3.5.0/usb-serial-for-android-3.5.0.pom
     Required by:
         project :app
...
```

By checking the link is broken https://jitpack.io/com/github/mik3y/usb-serial-for-android/3.5.0/usb-serial-for-android-3.5.0.pom
Path is broken from 3.5.0

Please help fix the link...

Best regards

Nancy

**Comment by nancwang** [comment]
Found solution! add 'v' before 3.5.0 solve the issue.
from
implementation 'com.github.mik3y:usb-serial-for-android:3.5.0
to
implementation 'com.github.mik3y:usb-serial-for-android:v3.5.0

**Comment by kai-morich** [comment]
Should work with and without v. 
For whatever reason the non-v build was missing on jitpack.io
I triggered it manually.
