### ISSUE TITLE
Always get Connection Lost from Serial USB Terminal app

### ISSUE THREAD

**Issue by sintyasin** [kai-morich/SimpleUsbTerminal#63]
Hello, 
I try to download your [Serial USB Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal) app and connect my Wavecom Fastrack (MULTIBAND  900E  1800). It runs well most of the day until today, when i tried to dial USSD with command AT+CUSD, it always show connection lost, but after i reconnect the device, it shows the USSD reply. Why is this happening? And how can i fix this? It also happen in my code which use your library, it shows this error "USB get_status request failed". So i tried to debug it with you apps, and the apps show a similar error of disconnecting when i dial USSD.

Thank you in advance
![IMG_20231106_172416](https://github.com/kai-morich/SimpleUsbTerminal/assets/25153121/a8455f4b-773f-43cf-ba7a-40dddc84a876)

![telegram-cloud-photo-size-5-6219655713614052523-y](https://github.com/kai-morich/SimpleUsbTerminal/assets/25153121/e99d0979-f752-4638-842c-40e0b7618710)

**Comment by kai-morich** [comment]
maybe power supply from your Android device is too weak

**Comment by sintyasin** [comment]
is there any ways / configuration that i can make to give more power?
But i also try connecting the device to my Mac and also got disconnected.

**Comment by kai-morich** [comment]
You should try with external power supply

**Comment by sintyasin** [comment]
Okay thanks, let me try it later 🙏
