### ISSUE TITLE
[Feature Suggestion] store buffer before clearing when filled

### ISSUE THREAD

**Issue by ericoporto** [kai-morich/SimpleUsbTerminal#7]
Hey, thanks for building a pretty good software, it really works with the USB otg device and a serial converter on my phone.

I would like to leave the phone connected to an appliance that's continuously sending information, in a csv file like output, with a new "row" being output each five seconds, unattended. For this, a minimal implementation I can think is once a buffer is filled it would write a file to the phone storage and start a new buffer. I would use it to leave the phone connected to it for two or more days, and pick it up later.

**Comment by kai-morich** [comment]
I want to keep this a simple example app showing the usage of usb-serial-for-android library. 

In my SerialUsbTerminal app I will add such *logging* mode as next feature
