### ISSUE TITLE
Is possible to send a command with the format all in hex

### ISSUE THREAD

**Issue by HarizahSyawal** [kai-morich/SimpleUsbTerminal#70]
Hello Kai currently my device that i communicate with, based on the specs need to send a command all in hex for example : 
Send command API Version [ReqId=1] (len=4): [#A1] 23 41 31 95
Recv (len=7): [#A1] 23 41 31 01 03 01 9a
since your library at the end when write a data, need to getBytes. Is it possible to adapt with my device specs to send all command in hex format ?

**Comment by kai-morich** [comment]
you could try with https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/util/HexDump.java to convert between HEX and bytes
