### ISSUE TITLE
Usb permission 

### ISSUE THREAD

**Issue by Mohamadraad** [kai-morich/SimpleUsbTerminal#81]
How can I handle USB permissions more effectively in my code? Currently, even after selecting the 'Always allow' checkbox, I need to grant permission again every time I detach and reattach the USB device. Is there a way to fix this issue so the permission persists?

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified DevicesFragment.java to handle USB permissions more effectively by using UsbPermission class and SharedPreferences to store and retrieve permission states. This allows the app to remember previously granted permissions, reducing the need for repeated permission requests.

You can review changes in this commit: https://github.com/wwqwq2313/kai-morich-SimpleUsbTerminal-81/commit/c85c09225902578c9bc6b04a288122441de116fa.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
